apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  labels:
    app: wordpress
data:
  WORDPRESS_DATABASE_HOST: "mysql-svc"
  WORDPRESS_DATABASE_NAME: "wordpress"
  WORDPRESS_DATABASE_PORT_NUMBER: "3306"