apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: "standard"
  # Descomente e ajuste o storageClassName conforme disponível no seu cluster.
  # Para descobrir: oc get storageclass
